from os import system
from time import sleep
import sys
import time

from datetime import datetime

def login():
    Login = input("tracking server code : ") 
    time.sleep(2)

if __name__ == "__main__":
    login()

time.sleep(5)

def print_colored(text, color, end='\n'):
    colors = {'red': '\x1b[31m', 'green': '\x1b[32m', 'white': '\x1b[33m', 'blue': '\x1b[34m',}
    reset = '\x1b[0m'
    sys.stdout.write(colors.get(color, '') + text + reset + end)

print_colored('eta name="description" content="SWIFT basic tracking of your wire transfer and GPI status in certain banks. Use UETR or Sender&amp;#039;s reference', color='red')
time.sleep(0.1)
print_colored('Other addresses for www.db.com (scanned)"', color='red')
time.sleep(0.1)
print_colored('92.123.103.97 2a02:26f0:d8::1740:c30 2a02:26f0:d8::1740:c49r', color='red')
time.sleep(0.1)
print_colored('DNS record for 92.123.103.82: a92-123-103-82.deploy.static.akamaitechnologies.com', color='red')
time.sleep(0.1)
print_colored('DNS record for 92.123.103.82: a92-123-103-82.deploy.static.akamaitechnologies.com', color='red')
time.sleep(0.1)
print_colored('Discovered open port 146/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 146/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3998/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8899/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 500/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 6565/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2022/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('Discovered open port 6129/tcp on 92.123.103.82', color='red')
time.sleep(0.1)
print_colored('500/tcp   open  isakmp', color='red')
time.sleep(0.1)
print_colored('514/tcp   open  shell', color='red')
time.sleep(0.1)
print_colored('545/tcp   open  ekshell', color='red')
time.sleep(0.1)
print_colored('554/tcp   open  rtsp', color='red')
time.sleep(0.1)
print_colored('2042/tcp  open  csis', color='red')
time.sleep(0.1)
print_colored('2048/tcp  open  dls-monitor', color='red')
time.sleep(0.1)
print_colored('2049/tcp  open  nfs', color='red')
time.sleep(0.1)
print_colored('2065/tcp  open  dlsrpn', color='red')
time.sleep(0.1)
print_colored('2099/tcp  open  h2250-annex-g', color='red')
time.sleep(0.1)
print_colored('2100/tcp  open  amiganetfs', color='red')
time.sleep(0.1)
print_colored('6666/tcp  open  irc', color='red')
time.sleep(0.1)
print_colored('6580/tcp  open  parsec-master', color='red')
time.sleep(0.1)
print_colored('49400/tcp open  compaqdiag', color='red')
time.sleep(0.1)
print_colored('correction done: 1 IP address (1 host up)', color='red')
time.sleep(5)
print_colored('Starting Nmap 7.80 ( https://nmap.org ) at PDT', color='red')
time.sleep(5)
print_colored('Warning: Hostname www.db.com resolves to 4 IPs. Using 23.44.51.138.', color='red')
time.sleep(0.1)
print_colored('Initiating Ping Scan at 00:22', color='red')
time.sleep(0.1)
print_colored('Scanning www.db.com (23.44.51.138) [2 ports]', color='red')
time.sleep(0.1)
print_colored('Completed Ping Scan at 00:22, 0.10s elapsed (1 total hosts)', color='red')
time.sleep(0.1)
print_colored('Initiating Parallel DNS resolution of 1 host. at 00:22', color='red')
time.sleep(0.1)
print_colored('Completed Parallel DNS resolution of 1 host. at 00:22, 0.10s elapsed', color='red')
time.sleep(0.1)
print_colored('DNS resolution of 1 IPs took 0.10s. Mode: Async [#: 1, OK: 1, NX: 0, DR: 0, SF: 0, TR: 1, CN: 0]', color='red')
time.sleep(0.1)
print_colored('Initiating Connect Scan at 00:22', color='red')
time.sleep(0.1)
print_colored('Scanning www.db.com (23.44.51.138) [1000 ports]', color='red')
time.sleep(0.1)
print_colored('Discovered open port 443/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 53/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 587/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 143/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 199/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1720/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 25/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8080/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 993/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 995/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8888/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3389/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1025/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 113/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 23/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 554/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 110/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 5900/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 80/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 256/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 135/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3306/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8089/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 51493/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1131/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8042/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1687/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 22/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 82/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1070/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 783/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 23502/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2222/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 5906/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 513/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1102/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3918/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 5050/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1034/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1521/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2909/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Increasing send delay for 23.44.51.138 from 0 to 5 due to 13 out of 42 dropped probes since last increase.', color='red')
time.sleep(0.1)
print_colored('Discovered open port 311/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 445/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 12174/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2869/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 139/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1723/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 21/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 19101/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1061/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 9002/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2005/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2604/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1434/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2998/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8291/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2701/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1052/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2042/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 7200/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3828/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8090/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2251/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1105/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 49167/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 111/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 8400/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 4000/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1000/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2383/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 99/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 3/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1277/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 6565/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 2065/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 4445/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1097/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 9003/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 20828/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 5269/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('Discovered open port 1310/tcp on 23.44.51.138', color='red')
time.sleep(0.1)
print_colored('51103/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('51493/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('52673/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('52822/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('52848/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('52869/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('54045/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('54328/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('55055/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('55056/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('55555/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('55600/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('56737/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('56738/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('57294/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('57797/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('58080/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('60020/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('60443/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('61532/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('61900/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('62078/tcp open  iphone-sync          syn-ack', color='green')
time.sleep(0.1)
print_colored('63331/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('64623/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('64680/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('65000/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('65129/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('65389/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('Other addresses for www.db.com (not scanned): 23.44.51.200 2600:140b:400::172d:32fa 2600:140b:400::172d:330a', color='green')
time.sleep(0.1)
print_colored('rDNS record for 23.44.51.138: a23-44-51-138.deploy.static.akamaitechnologies.com', color='green')
time.sleep(0.1)
print_colored('Scanned at 2024-07-14 00:22:11 PDT for 28s', color='green')
time.sleep(0.1)
print_colored('9111/tcp  open  DragonIDSConsole     syn-ack', color='green')
time.sleep(0.1)       
print_colored('9200/tcp  open  wap-wsp              syn-ack', color='green')
time.sleep(0.1)
print_colored('9502/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9594/tcp  open  msgsys               syn-ack', color='green')
time.sleep(0.1)
print_colored('9595/tcp  open  pds                  syn-ack', color='green')
time.sleep(0.1)
print_colored('9618/tcp  open  condor               syn-ack', color='green')
time.sleep(0.1)
print_colored('9666/tcp  open  zoomcp               syn-ack', color='green')
time.sleep(0.1)
print_colored('9876/tcp  open  sd                   syn-ack', color='green')
time.sleep(0.1)
print_colored('9877/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9503/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9666/tcp  open  zoomcp               syn-ack', color='green')
time.sleep(0.1)
print_colored('9876/tcp  open  sd                   syn-ack', color='green')
time.sleep(0.1)
print_colored('9877/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9535/tcp  open  man                  syn-ack', color='green')
time.sleep(0.1)
print_colored('9666/tcp  open  zoomcp               syn-ack', color='green')
time.sleep(0.1)
print_colored('9876/tcp  open  sd                   syn-ack', color='green')
time.sleep(0.1)
print_colored('9877/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9575/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9593/tcp  open  cba8                 syn-ack', color='green')
time.sleep(0.1)
print_colored('9594/tcp  open  msgsys               syn-ack', color='green')
time.sleep(0.1)
print_colored('9595/tcp  open  pds                  syn-ack', color='green')
time.sleep(0.1)
print_colored('9618/tcp  open  condor               syn-ack', color='green')
time.sleep(0.1)
print_colored('9666/tcp  open  zoomcp               syn-ack', color='green')
time.sleep(0.1)
print_colored('9876/tcp  open  sd                   syn-ack', color='green')
time.sleep(0.1)
print_colored('9877/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9878/tcp  open  kca-service          syn-ack', color='green')
time.sleep(0.1)
print_colored('9898/tcp  open  monkeycom            syn-ack', color='green')
time.sleep(0.1)
print_colored('9900/tcp  open  iua                  syn-ack', color='green')
time.sleep(0.1)
print_colored('9917/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9929/tcp  open  nping-echo           syn-ack', color='green')
time.sleep(0.1)
print_colored('9943/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9944/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9968/tcp  open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('9998/tcp  open  distinct32           syn-ack', color='green')
time.sleep(0.1)
print_colored('9999/tcp  open  abyss                syn-ack', color='green')
time.sleep(0.1)
print_colored('10000/tcp open  snet-sensor-mgmt     syn-ack', color='green')
time.sleep(0.1)
print_colored('10001/tcp open  scp-config           syn-ack', color='green')
time.sleep(0.1)
print_colored('10002/tcp open  documentum           syn-ack', color='green')
time.sleep(0.1)
print_colored('10003/tcp open  documentum_s         syn-ack', color='green')
time.sleep(0.1)
print_colored('10004/tcp open  emcrmirccd           syn-ack', color='green')
time.sleep(0.1)
print_colored('10009/tcp open  swdtp-sv             syn-ack', color='green')
time.sleep(0.1)
print_colored('10010/tcp open  rxapi                syn-ack', color='green')
time.sleep(0.1)
print_colored('10012/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10024/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10025/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10082/tcp open  amandaidx            syn-ack', color='green')
time.sleep(0.1)
print_colored('10180/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10215/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10243/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10566/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10616/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10617/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10621/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10626/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10628/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10629/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('10778/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('11110/tcp open  sgi-soap             syn-ack', color='green')
time.sleep(0.1)
print_colored('11111/tcp open  vce                  syn-ack', color='green')
time.sleep(0.1)
print_colored('11967/tcp open  sysinfo-sp           syn-ack', color='green')
time.sleep(0.1)
print_colored('12000/tcp open  cce4x                syn-ack', color='green')
time.sleep(0.1)
print_colored('12174/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('12265/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('12345/tcp open  netbus               syn-ack', color='green')
time.sleep(0.1)
print_colored('13456/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('13722/tcp open  netbackup            syn-ack', color='green')
time.sleep(0.1)
print_colored('13782/tcp open  netbackup            syn-ack', color='green')
time.sleep(0.1)
print_colored('13783/tcp open  netbackup            syn-ack', color='green')
time.sleep(0.1)
print_colored('14000/tcp open  scotty-ft            syn-ack', color='green')
time.sleep(0.1)
print_colored('14238/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('14441/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('14442/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('15000/tcp open  hydap                syn-ack', color='green')
time.sleep(0.1)
print_colored('15002/tcp open  onep-tls             syn-ack', color='green')
time.sleep(0.1)
print_colored('15003/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('15004/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('15660/tcp open  bex-xr               syn-ack', color='green')
time.sleep(0.1)
print_colored('15742/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('16000/tcp open  fmsas                syn-ack', color='green')
time.sleep(0.1)
print_colored('16001/tcp open  fmsascon             syn-ack', color='green')
time.sleep(0.1)
print_colored('16012/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('16016/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('16018/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('16080/tcp open  osxwebadmin          syn-ack', color='green')
time.sleep(0.1)
print_colored('16992/tcp open  amt-soap-http        syn-ack', color='green')
time.sleep(0.1)
print_colored('16993/tcp open  amt-soap-https       syn-ack', color='green')
time.sleep(0.1)
print_colored('17877/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('17988/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('18040/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('18101/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('18988/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('19101/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('19283/tcp open  keysrvr              syn-ack', color='green')
time.sleep(0.1)
print_colored('19315/tcp open  keyshadow            syn-ack', color='green')
time.sleep(0.1)
print_colored('91780/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('19801/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('19842/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('20000/tcp open  dnp                  syn-ack', color='green')
time.sleep(0.1)
print_colored('20005/tcp open  btx                  syn-ack', color='green')
time.sleep(0.1)
print_colored('20031/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('20221/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('20222/tcp open  ipulse-ics           syn-ack', color='green')
time.sleep(0.1)
print_colored('20828/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('21571/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('22939/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('23502/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('24444/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('24800/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('25734/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('25735/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('26214/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('27000/tcp open  flexlm0              syn-ack', color='green')
time.sleep(0.1)
print_colored('27352/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('27353/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('27355/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('27356/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('27715/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('28201/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('30000/tcp open  ndmps                syn-ack', color='green')
time.sleep(0.1)
print_colored('30718/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('30951/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('31038/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('31337/tcp open  Elite                syn-ack', color='green')
time.sleep(0.1)
print_colored('32768/tcp open  filenet-tms          syn-ack', color='green')
time.sleep(0.1)
print_colored('32769/tcp open  filenet-rpc          syn-ack', color='green')
time.sleep(0.1)
print_colored('32770/tcp open  sometimes-rpc3       syn-ack', color='green')
time.sleep(0.1)
print_colored('32771/tcp open  sometimes-rpc5       syn-ack', color='green')
time.sleep(0.1)
print_colored('32772/tcp open  sometimes-rpc7       syn-ack', color='green')
time.sleep(0.1)
print_colored('32773/tcp open  sometimes-rpc9       syn-ack', color='green')
time.sleep(0.1)
print_colored('32774/tcp open  sometimes-rpc11      syn-ack', color='green')
time.sleep(0.1)
print_colored('32775/tcp open  sometimes-rpc13      syn-ack', color='green')
time.sleep(0.1)
print_colored('32776/tcp open  sometimes-rpc15      syn-ack', color='green')
time.sleep(0.1)
print_colored('32777/tcp open  sometimes-rpc17      syn-ack', color='green')
time.sleep(0.1)
print_colored('32778/tcp open  sometimes-rpc19      syn-ack', color='green')
time.sleep(0.1)
print_colored('32779/tcp open  sometimes-rpc21      syn-ack', color='green')
time.sleep(0.1)
print_colored('32780/tcp open  sometimes-rpc23      syn-ack', color='green')
time.sleep(0.1)
print_colored('32781/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('12782/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('32783/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('32784/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('32785/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('33354/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('33899/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('34571/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('34572/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('34573/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('35500/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('38292/tcp open  landesk-cba          syn-ack', color='green')
time.sleep(0.1)
print_colored('40193/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('40911/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('41511/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('42510/tcp open  caerpc               syn-ack', color='green')
time.sleep(0.1)
print_colored('44176/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('44442/tcp open  coldfusion-auth      syn-ack', color='green')
time.sleep(0.1)
print_colored('44501/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('55100/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('48080/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49152/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49153/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49154/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49155/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49156/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49157/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49158/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49159/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49160/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49161/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49163/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49165/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49167/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49175/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49176/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('49400/tcp open  compaqdiag           syn-ack', color='green')
time.sleep(0.1)
print_colored('49999/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50000/tcp open  ibm-db2              syn-ack', color='green')
time.sleep(0.1)
print_colored('50001/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50002/tcp open  iiimsf               syn-ack', color='green')
time.sleep(0.1)
print_colored('50003/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50006/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50300/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50389/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50500/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50636/tcp open  unknown              syn-ack', color='green')
time.sleep(0.1)
print_colored('50800/tcp open  unknown              syn-ack', color='green')
time.sleep(5)
black = "\033[0;30m"
purple = "\033[0;35m"
blue = "\033[0;34m"
green = "\033[0;32m"
white = "\033[0;37m"

def clear():
    system('clear')

def scrollTxt(text, color, speed):
    if color == "":
        for char in text:
            sys.stdout.write(char)
            sys.stdout.flush()
            sleep(speed)
        print()
    else:
        print(color, end="")
        for char in text:
            sys.stdout.write(char)
            sys.stdout.flush()
            sleep(speed)
        print()
        print(white, end="")
  
print("")

time.sleep(2)

scrollTxt("Server-side tracking has emerged as an effective solution, addressing many of the challenges faced by ", blue, 0.03)

time.sleep(1)
scrollTxt("traditional client-side tagging and filling the gaps left by the third-party data collection methods of old", blue, 0.03)
time.sleep(2)


print_colored('eta name="description" content="SWIFT basic tracking of your wire transfer and GPI status in certain banks. Use UETR or Sender&amp;#039;s reference', color='red')
time.sleep(0.1)

print_colored('[!] Internet hack activity soars due to automatic worm attacks', color='red')
print_colored(' [!]We have all read about cyberterrorists, identity thieves, industrial saboteurs, credit card crooks, Web site vandals, hackers, crackers and script kiddies', color='red')
print_colored('                                                              /\ ', color='red')
print_colored('                                                             //\\ ', color='red')
print_colored('                                                             |/\| ', color='red')
print_colored('                                                             |\/|', color='red')
print_colored(' ╔══╗  ╔══╗  ╔════════╗  ╔═════════╗  ╔════════╗          (\.|\/|./)         ╔════════╗   ╔══╗  ╔══╗   ╔════════╗', color='red')
print_colored(' ║██║  ║██║  ║████████║  ║█████████║  ║████████║       (\.gkc|\/|gkc./)      ║████████║   ║██║  ║██║   ║████████║', color='red')
print_colored(' ║██║ ║██║   ║██║  ║██║  ║██║   ║██║  ║██║╔════╗      (\kong||||||gkc /)     ║██║╔════╗   ║██║ ║██║    ║██║  ║██║', color='red')
print_colored(' ║██║██║     ║██║  ║██║  ║██║   ║██║  ║██║║█║██║      (\konga|/\| gkc-/)     ║██║║█║██║   ║██║██║      ║██║', color='red')
print_colored(' ║██║ ║██║   ║██║  ║██║  ║██║   ║██║  ║██║  ║██║     (\ kongali1720gkc/)     ║██║  ║██║   ║██║ ║██║    ║██║   ██║', color='red')
print_colored(' ║██║  ║██║  ║████████║  ║██║   ║██║  ║████████║       \ kong \/ -gkc /      ║████████║   ║██║  ║██║   ║████████║', color='red')
print_colored(' ╚══╝  ╚══╝  ╚════════╝  ╚══╝   ╚══╝  ╚════════╝        \____/\/\____/       ╚════════╝   ╚══╝  ╚══╝   ╚════════╝', color='red')
print_colored('                    {C} Coded By - kongali1720 - gatotkaca   \/\/  * swift *gpi *ipip *fin ', color='red')
print_colored('                                                              \/', color='red')



from datetime import datetime

def get_current_datetime():
    # Get the current date and time
    now = datetime.now()
    
    # Format the date and time as a string
    current_time = now.strftime("%Y-%m-%d %H:%M:%S")
    
    return current_time

if __name__ == "__main__":
    current_time = get_current_datetime()
    print(f"Current Date and Time: {current_time}")

time.sleep(5)

import time
import sys

total = 1007  # total number to reach
bar_length = 99  # should be less than 100
for i in range(total+1):
    percent = 100.0*i/total
    sys.stdout.write('\r')
    sys.stdout.write("processing: [{:{}}] {:>3}%"
                     .format('='*int(percent/(100.0/bar_length)),
                             bar_length, int(percent)))
    sys.stdout.flush()
    time.sleep(0.002)
    
print("")

if __name__ == "__main__":
    current_time = get_current_datetime()
    print(f"{current_time}")

def progress_bar(progress, total):
    percent = 100 * (progress / float(total))
    bar = '█' * int(percent) + '-' * (100 - int(percent))
    print(f"\r|{bar}| {percent:.2f}%", end="\r")
            
numbers = [x * 5 for x in range(2000, 3000)]

results = []

time.sleep(5)


print("")

scrollTxt("----------------------------------------------WELCOME TO SWIFT------------------------------------------", blue, 0.03)
time.sleep(2)
print("$  global_server/start")

time.sleep(2)
def login():
    Login = input("Login     : ")
    time.sleep(2)
    Password = input("Password  : ")
    time.sleep(2)

if __name__ == "__main__":
    login()

time.sleep(5)

def progress_bar(iteration, total, prefix='', suffix='', length=30, fill='█'):
    percent = ("{0:.1f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    sys.stdout.write(f'\r{prefix} |{bar}| {percent}% {suffix}')
    sys.stdout.flush()

# Example usage
total_iterations = 100
for i in range(total_iterations + 1):
    time.sleep(0.05)  # Simulate some work
    progress_bar(i, total_iterations, prefix='Progress ', suffix='', length=93)#setelah suffix bisa ditambahin kata2

print("\nCONNECTED ")

import datetime

# get the current date and time
now = datetime.datetime.now()

print(now)

time.sleep(5)

import sys
def print_colored(text, color, end='\n'):
    colors = {'red': '\x1b[31m', 'green': '\x1b[32m', 'white': '\x1b[33m', 'blue': '\x1b[34m',}
    reset = '\x1b[0m'
    sys.stdout.write(colors.get(color, '') + text + reset + end)

print_colored('& global_server/mt103/convert/blockchain/btc', color='red')

time.sleep(5)
def login():
    trn = input("TRN              : ")
    time.sleep(2)
    downloadingcode = input("DOWNLOADING CODE : ")
    time.sleep(2)
    reference= input("REFERENCE CODE   : ")
    time.sleep(2)

if __name__ == "__main__":
    login()

scrollTxt("------------------------------------------------DOWNLOADING---------------------------------------------", blue, 0.03)

time.sleep(5)

def progress_bar(iteration, total, prefix='', suffix='', length=30, fill='█'):
    percent = ("{0:.1f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    sys.stdout.write(f'\r{prefix} |{bar}| {percent}% {suffix}')
    sys.stdout.flush()

# Example usage
total_iterations = 100
for i in range(total_iterations + 1):
    time.sleep(0.05)  # Simulate some work
    progress_bar(i, total_iterations, prefix='Progress ', suffix='', length=93)#setelah suffix bisa ditambahin kata2

print("\nDOWNLOAD COMPLETED ")

import datetime

# get the current date and time
now = datetime.datetime.now()

print(now)

time.sleep(5)

print("")

scrollTxt("------------------------------------------------CONVERTIING---------------------------------------------", blue, 0.03)

time.sleep(5)

def progress_bar(iteration, total, prefix='', suffix='', length=30, fill='█'):
    percent = ("{0:.1f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    sys.stdout.write(f'\r{prefix} |{bar}| {percent}% {suffix}')
    sys.stdout.flush()

# Example usage
total_iterations = 100
for i in range(total_iterations + 1):
    time.sleep(0.05)  # Simulate some work
    progress_bar(i, total_iterations, prefix='Progress ', suffix='', length=93)#setelah suffix bisa ditambahin kata2

print("\nDOWNLOAD COMPLETED ")

import datetime

# get the current date and time
now = datetime.datetime.now()

print(now)

time.sleep(5)

print("")

def login():
    walletaddres = input("WALLET ADDRESS : ")
    time.sleep(2)
    finalcode =input("FINAL CODE     : ")
    releasecode = input("RELEASE CODE   :")
    time.sleep(2)
    pin = input("PIN CODE       : ")
    time.sleep(2)

if __name__ == "__main__":
    login()

def progress_bar(iteration, total, prefix='', suffix='', length=30, fill='█'):
    percent = ("{0:.1f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    sys.stdout.write(f'\r{prefix} |{bar}| {percent}% {suffix}')
    sys.stdout.flush()

# Example usage
total_iterations = 100
for i in range(total_iterations + 1):
    time.sleep(0.05)  # Simulate some work
    progress_bar(i, total_iterations, prefix='Progress ', suffix='', length=93)#setelah suffix bisa ditambahin kata2

print("\nCONVERT COMPLETED ")

import datetime

# get the current date and time
now = datetime.datetime.now()

print(now)

time.sleep(5)

print("")
